I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    show s1 p1 zoom 0.5
Exception: Image 's1 p1' does not accept attributes 'zoom 0 .5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    show s1 p1 zoom 0.5
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "C:\Users\Leonhard\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 's1 p1' does not accept attributes 'zoom 0 .5'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Howdey Abbey 1.0
Tue Jan  2 12:39:50 2024
